general.import = [
  "./theme.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 16

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

[scrolling]
history = 10_000
multiplier = 3

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

  [window.class]
  general = "Alacritty"
  instance = "Alacritty"

  [window.padding]
  x = 10
  y = 10
